name: Build action

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/actions/setup-action

    - name: Build
      run: ./gradlew detekt :core:apiCheck test build :intellij-plugin:buildPlugin
      shell: bash