name: Build action

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup
      uses: ./.github/actions/setup-action

    - name: Build
      run: |
        ./gradlew detekt :core:apiCheck test build :intellij-plugin:plugin:buildPlugin
        ./samples/gradle-project/gradlew build
      shell: bash