[versions]
# Platforms
kotlin = "2.1.0"
jvm = "21"

# Libraries
kmp-serialization = "1.7.3"
gradle-publish = "1.3.0"
detekt = "1.23.7"
maven-publish = "0.30.0"
intellij = "2.2.0"

# Releases
release = "1.0.2"

[libraries]
kmp-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kmp-serialization" }
kmp-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
kmp-kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kmp-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
intellij = { id = "org.jetbrains.intellij.platform", version.ref = "intellij" }