name: Build Workflow

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: ./.github/workflows/build-action.yml
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gradle-plugin
          path: ./gradle-plugin/build/libs/*.jar