name: Release Workflow

on:
  push:
    branches:
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/setup-action

      - name: Download core artifacts from master
        uses: actions/download-artifact@v4
        with:
          name: core-master
          path: ./core/build/libs

      - name: Download gradle plugin artifacts from master
        uses: actions/download-artifact@v4
        with:
          name: gradle-plugin-master
          path: ./gradle-plugin/build/libs

      - name: Publish gradle plugin
        run: |
          ./gradlew :gradle-plugin:publishPlugins \
          -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} \
          -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} \

      - name: Publish to MavenCentral
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_CENTRAL_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY_CONTENTS }}

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./gradle-plugin/build/libs/*.jar
            ./core/build/libs/*.jar