name: Master Workflow

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-action

      - name: Upload core artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core
          path: ./core/build/libs/*.jar

      - name: Upload gradle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gradle-plugin
          path: ./gradle-plugin/build/libs/*.jar