name: Master Workflow

on:
  pull_request:
    branches-ignore:
      - '*release*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.ref == 'refs/heads/master' && 'master' || 'pr' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build-action

      - name: Upload core artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core-${{ BRANCH_NAME }}
          path: ./core/build/libs/*.jar

      - name: Upload gradle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gradle-plugin-${{ BRANCH_NAME }}
          path: ./gradle-plugin/build/libs/*.jar