name: Master Workflow

on:
  pull_request:
    branches-ignore:
      - '*release*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build-action

      - name: Upload core artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core-${{ github.head_ref }}
          path: ./core/build/libs/*.jar

      - name: Upload gradle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gradle-plugin-${{ github.head_ref }}
          path: ./gradle-plugin/build/libs/*.jar